#!/usr/bin/env bash

requirement_files=('requirements.txt' 'requirements-dev.txt')

if ! [[ -d ".venv/" ]]; then
	echo "creating venv"
	python3 -m virtualenv .venv
	source .venv/bin/activate
	for requirement in "${requirement_files[@]}"; do
		if [ -f "$requirement" ]; then
			echo "installing $requirement"
			python -m pip install -r "$requirement"
		fi
	done
else
	source .venv/bin/activate
fi
